export interface Verse {
    id: number;
    hint: string;
    answer: string;
    category?: string;
}

export const createVersesTable = `
    CREATE TABLE IF NOT EXISTS verses (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        hint TEXT NOT NULL,
        answer TEXT NOT NULL,
        category TEXT
    );
    DELETE FROM verses;
`;

export const initialVerses = `
    INSERT INTO verses (hint, answer, category) VALUES
    ('I am the way, and the truth, and the life. No one comes to the Father except through me.', 'Jesus', 'New Testament'),
    ('For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.', 'John', 'New Testament'),
    ('Eye for eye, tooth for tooth, hand for hand, foot for foot, burn for burn, wound for wound, bruise for bruise', 'Moses', 'Old Testament'),
    ('I am the good shepherd. The good shepherd lays down his life for the sheep.', 'Jesus', 'New Testament'),
    ('I heard thy voice in the garden, and I was afraid, because I was naked; and I hid myself', 'Adam', 'Old Testament'),
    ('Behold the Lamb of God who takes away the sin of the world', 'John', 'New Testament'),
    ('From then on ___ watched for an opportunity to hand him over.', 'Judas', 'New Testament'),
    ('I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing', 'John', 'New Testament'),
    ('I can do all things through Christ who strengthens me', 'Paul', 'New Testament'),
    ('Are You the King of the Jews?', 'Pilate', 'New Testament'),
    ('With man it is impossible, but not with God. For all things are possible with God.', 'Jesus', 'New Testament'),
    ('For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future', 'Jeremiah', 'Old Testament'),
    ('But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint', 'Isaiah', 'Old Testament'),
    ('For I desire mercy, not sacrifice, and the knowledge of God rather than burnt offerings', 'Hosea', 'Old Testament'),
    ('But blessed is the one who trusts in the Lord, whose confidence is in him', 'Jeremiah', 'Old Testament'),
    ('And ___ remembered the word of Jesus who had said to him, "Before the rooster crows, you will deny Me three times." So he went out and wept bitterly.', 'Peter', 'New Testament'),
    ('As for you, you must keep my covenant, you and your descendants after you for the generations to come.', 'Abraham', 'Old Testament'),
    ('Watch out for false prophets. They come to you in sheep''s clothing, but inwardly they are ferocious wolves. By their fruit you will recognize them', 'Jesus', 'New Testament'),
    ('My Lord and my God!', 'Thomas', 'New Testament'),
    ('Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.', 'Jesus', 'New Testament'),
    ('Am I my brother''s keeper?', 'Cain', 'Old Testament'),
    ('Here am I. Send me!', 'Isaiah', 'Old Testament'),
    ('Lord, if it''s you, tell me to come to you on the water.', 'Peter', 'New Testament'),
    ('My God, my God, why have you forsaken me?', 'David', 'Old Testament'),
    ('Unless I see the nail marks in his hands and put my finger where the nails were, and put my hand into his side, I will not believe.', 'Thomas', 'New Testament'),
    ('Speak, Lord, for your servant is listening.', 'Samuel', 'Old Testament'),
    ('Lord, don''t you care that my sister has left me to do the work by myself?', 'Martha', 'New Testament'),
    ('The spirit is willing, but the flesh is weak.', 'Jesus', 'New Testament'),
    ('How can a man be born when he is old?', 'Nicodemus', 'New Testament'),
    ('Lord, to whom shall we go? You have the words of eternal life.', 'Peter', 'New Testament'),
    ('Is anything too hard for the Lord?', 'Abraham', 'Old Testament'),
    ('Choose for yourselves this day whom you will serve But as for me and my household, we will serve the Lord.', 'Joshua', 'Old Testament'),
    ('Let my people go', 'Moses', 'Old Testament'),
    ('Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go', 'Joshua', 'Old Testament'),
    ('Entreat me not to leave you, or to turn back from following you; For wherever you go, I will go', 'Ruth', 'Old Testament'),
    ('You come against me with sword and spear and javelin, but I come against you in the name of the Lord Almighty', 'David', 'Old Testament'),
    ('Give your servant a discerning heart to govern your people and to distinguish between right and wrong', 'Solomon', 'Old Testament'),
    ('Lord, if you are willing, you can make me clean', 'Leper', 'New Testament'),
    ('Woman, why do you involve me? My hour has not yet come', 'Jesus', 'New Testament'),
    ('Silver or gold I do not have, but what I do have I give you', 'Peter', 'New Testament'),
    ('Get behind me Satan! You are a stumbling block to me', 'Jesus', 'New Testament'),
    ('Can these bones live?', 'Ezekiel', 'Old Testament'),
    ('The Lord is my shepherd, I shall not want', 'David', 'Old Testament'),
    ('My soul magnifies the Lord, and my spirit rejoices in God my Savior', 'Mary', 'New Testament'),
    ('Lord, I believe; help my unbelief!', 'Father', 'New Testament'),
    ('Remember now your Creator in the days of your youth', 'Solomon', 'Old Testament'),
    ('Who do you say that I am?', 'Jesus', 'New Testament'),
    ('I have fought the good fight, I have finished the race, I have kept the faith', 'Paul', 'New Testament'),
    ('Behold, I stand at the door and knock', 'Jesus', 'New Testament'),
    ('The Lord gave and the Lord has taken away; blessed be the name of the Lord', 'Job', 'Old Testament'),
    ('Speak, for your servant hears', 'Samuel', 'Old Testament'),
    ('Here I am, send me!', 'Isaiah', 'Old Testament'),
    ('Master, we have worked all night and caught nothing', 'Peter', 'New Testament'),
    ('Today, if you hear his voice, do not harden your hearts', 'David', 'Old Testament'),
    ('Can anything good come out of Nazareth?', 'Nathanael', 'New Testament'),
    ('If I perish, I perish', 'Esther', 'Old Testament'),
    ('My grace is sufficient for you, for my power is made perfect in weakness', 'Jesus', 'New Testament'),
    ('As for me and my house, we will serve the Lord', 'Joshua', 'Old Testament'),
    ('I know that my redeemer lives', 'Job', 'Old Testament'),
    ('Could you not watch with me for one hour?', 'Jesus', 'New Testament'),
    ('Unless the Lord builds the house, those who build it labor in vain', 'Solomon', 'Old Testament'),
    ('Lord, you know all things; you know that I love you', 'Peter', 'New Testament'),
    ('Should you not also have had compassion on your fellow servant?', 'Jesus', 'New Testament'),
    ('Naked I came from my mother''s womb, and naked shall I return', 'Job', 'Old Testament'),
    ('What is truth?', 'Pilate', 'New Testament'),
    ('Where were you when I laid the foundations of the earth?', 'God', 'Old Testament'),
    ('Why do you call me good? No one is good except God alone', 'Jesus', 'New Testament'),
    ('How long will you waver between two opinions?', 'Elijah', 'Old Testament'),
    ('Can a mother forget the baby at her breast?', 'God', 'Old Testament'),
    ('Lord, to whom shall we go? You have the words of eternal life', 'Peter', 'New Testament'),
    ('Am I in the place of God?', 'Joseph', 'Old Testament'),
    ('You meant evil against me, but God meant it for good', 'Joseph', 'Old Testament'),
    ('How then can I do this great wickedness and sin against God?', 'Joseph', 'Old Testament'),
    ('Do not interpretations belong to God? Tell me your dreams', 'Joseph', 'Old Testament'),
    ('God will surely visit you, and you shall carry up my bones from here', 'Joseph', 'Old Testament'),
    ('I am Joseph! Is my father still alive?', 'Joseph', 'Old Testament'),
    ('Do not be afraid, for am I in God''s place?', 'Joseph', 'Old Testament'),
    ('The dream was given twice because the matter is fixed by God', 'Joseph', 'Old Testament'),
    ('Can we find anyone like this man, one in whom is the spirit of God?', 'Pharaoh', 'Old Testament'),
    ('I AM WHO I AM', 'God', 'Old Testament'),
    ('If you are the Son of God, command these stones to become bread', 'Satan', 'New Testament'),
    ('If you are the Son of God, throw yourself down, for it is written, He will command his angels concerning you', 'Satan', 'New Testament'),
    ('All these kingdoms I will give you, if you will fall down and worship me', 'Satan', 'New Testament'),
    ('Does Job fear God for nothing? Have you not put a hedge around him?', 'Satan', 'Old Testament'),
    ('Skin for skin! All that a man has he will give for his life', 'Satan', 'Old Testament'),
    ('Where is he who has been born king of the Jews? For we saw his star in the east', 'WiseMen', 'New Testament'),
    ('We have seen his star in the east and have come to worship him', 'WiseMen', 'New Testament'),
    ('We saw his star when it rose and have come to worship him', 'WiseMen', 'New Testament'),
    ('When they saw the star, they rejoiced exceedingly with great joy', 'WiseMen', 'New Testament');
    
    
    
`; 